export interface HeritageRecord {
  period: string;
  iconName: string;
  narrative: string;
  discipline: string;
}

export const legacyCollection: HeritageRecord[] = [
  { period: "1848", iconName: "Savitribai Phule", narrative: "India's first female teacher and social reformer.", discipline: "Education" },
  { period: "1883", iconName: "Anandibai Joshi", narrative: "First Indian female physician to study Western medicine.", discipline: "Medicine" },
  { period: "1889", iconName: "Pandita Ramabai", narrative: "Scholar and champion for women's education and rights.", discipline: "Social Work" },
  { period: "1905", iconName: "Suzanne RD Tata", narrative: "First woman in India to drive a car.", discipline: "Pioneer" },
  { period: "1917", iconName: "Annie Besant", narrative: "First woman president of the Indian National Congress.", discipline: "Politics" },
  { period: "1925", iconName: "Sarojini Naidu", narrative: "The Nightingale of India; poet and political activist.", discipline: "Politics" },
  { period: "1927", iconName: "Muthulakshmi Reddi", narrative: "First female legislator in British India.", discipline: "Politics" },
  { period: "1936", iconName: "Sarla Thakral", narrative: "First Indian woman to fly an aircraft.", discipline: "Aviation" },
  { period: "1937", iconName: "Vijaya Lakshmi Pandit", narrative: "First Indian woman to hold a cabinet post.", discipline: "Politics" },
  { period: "1942", iconName: "Aruna Asaf Ali", narrative: "Heroine of the 1942 Quit India Movement.", discipline: "Politics" },
  { period: "1944", iconName: "Asima Chatterjee", narrative: "First woman to receive a D.Sc. from an Indian University.", discipline: "Science" },
  { period: "1947", iconName: "Amrit Kaur", narrative: "First Health Minister of independent India.", discipline: "Politics" },
  { period: "1951", iconName: "Prem Mathur", narrative: "First Indian woman to become a commercial pilot.", discipline: "Aviation" },
  { period: "1953", iconName: "Vijayalakshmi Pandit", narrative: "First woman president of the UN General Assembly.", discipline: "Diplomacy" },
  { period: "1958", iconName: "Arati Saha", narrative: "First Asian woman to swim across the English Channel.", discipline: "Sports" },
  { period: "1963", iconName: "Sucheta Kriplani", narrative: "India's first woman Chief Minister (UP).", discipline: "Politics" },
  { period: "1966", iconName: "Indira Gandhi", narrative: "First and only female Prime Minister of India.", discipline: "Politics" },
  { period: "1966", iconName: "Reita Faria", narrative: "First Indian and Asian woman to win Miss World.", discipline: "Pioneer" },
  { period: "1970", iconName: "Kamaljit Sandhu", narrative: "First Indian woman to win a Gold at the Asian Games.", discipline: "Sports" },
  { period: "1972", iconName: "Kiran Bedi", narrative: "First woman to join the Indian Police Service (IPS).", discipline: "Public Service" },
  { period: "1978", iconName: "Anna Malhotra", narrative: "First woman IAS officer of independent India.", discipline: "Public Service" },
  { period: "1979", iconName: "Mother Teresa", narrative: "First Indian woman to win the Nobel Peace Prize.", discipline: "Social Work" },
  { period: "1984", iconName: "Bachendri Pal", narrative: "First Indian woman to reach the summit of Mt. Everest.", discipline: "Adventure" },
  { period: "1986", iconName: "Neerja Bhanot", narrative: "Youngest recipient of the Ashoka Chakra for bravery.", discipline: "Pioneer" },
  { period: "1989", iconName: "Justice Fathima Beevi", narrative: "First female judge appointed to the Supreme Court.", discipline: "Law" },
  { period: "1992", iconName: "Santosh Yadav", narrative: "First woman to scale Mt. Everest twice.", discipline: "Adventure" },
  { period: "1993", iconName: "Amrita Pritam", narrative: "Leading Punjabi poet and novelist.", discipline: "Literature" },
  { period: "1994", iconName: "Sushmita Sen", narrative: "First Indian woman to win the Miss Universe title.", discipline: "Pioneer" },
  { period: "1995", iconName: "Karnam Malleswari", narrative: "First Indian woman to win an Olympic medal.", discipline: "Sports" },
  { period: "1997", iconName: "Kalpana Chawla", narrative: "First Indian-born woman to go into space.", discipline: "Science" },
  { period: "1997", iconName: "Arundhati Roy", narrative: "First Indian woman to win the Booker Prize.", discipline: "Literature" },
  { period: "2000", iconName: "Bina Agarwal", narrative: "Economist focusing on gender and land rights.", discipline: "Science" },
  { period: "2004", iconName: "Mary Kom", narrative: "Legendary boxer and 6-time World Champion.", discipline: "Sports" },
  { period: "2005", iconName: "Sunita Williams", narrative: "Astronaut with Indian heritage; held space walk records.", discipline: "Science" },
  { period: "2007", iconName: "Pratibha Patil", narrative: "First woman President of India.", discipline: "Politics" },
  { period: "2009", iconName: "Saina Nehwal", narrative: "First Indian Olympic medalist in Badminton.", discipline: "Sports" },
  { period: "2009", iconName: "Meira Kumar", narrative: "First woman Speaker of the Lok Sabha.", discipline: "Politics" },
  { period: "2010", iconName: "Tessy Thomas", narrative: "The 'Missile Woman of India'; Director for Agni-IV.", discipline: "Science" },
  { period: "2011", iconName: "Mithali Raj", narrative: "Highest run-scorer in women's international cricket.", discipline: "Sports" },
  { period: "2013", iconName: "Arunima Sinha", narrative: "First female amputee to climb Mt. Everest.", discipline: "Adventure" },
  { period: "2014", iconName: "Ritu Karidhal", narrative: "Deputy Operations Director for Mars Mission.", discipline: "Science" },
  { period: "2016", iconName: "Deepa Malik", narrative: "First Indian woman to win a Paralympic medal.", discipline: "Sports" },
  { period: "2016", iconName: "P.V. Sindhu", narrative: "First Indian woman to win an Olympic Silver.", discipline: "Sports" },
  { period: "2018", iconName: "Hima Das", narrative: "First Indian athlete to win Gold at U-20 World track.", discipline: "Sports" },
  { period: "2019", iconName: "Gita Gopinath", narrative: "First female Chief Economist of the IMF.", discipline: "Science" },
  { period: "2021", iconName: "Falguni Nayar", narrative: "Founder of Nykaa; self-made billionaire.", discipline: "Pioneer" },
  { period: "2022", iconName: "Droupadi Murmu", narrative: "First tribal woman President of India.", discipline: "Politics" },
  { period: "2023", iconName: "Shiva Chauhan", narrative: "First woman officer deployed at Siachen Glacier.", discipline: "Pioneer" },
  { period: "2024", iconName: "Nigar Shaji", narrative: "Project Director of Aditya-L1 solar mission.", discipline: "Science" },
  { period: "2026", iconName: "Future Legend", narrative: "Continuing the legacy of brilliance and power.", discipline: "Pioneer" }
];